kind: Service
apiVersion: v1
metadata:
  name: apache-service
  namespace: test2
spec:
  type: ClusterIP
  ports:
  - name: apache-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache

