apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: test2
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.39
        ports:
        - containerPort: 80

