kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: test1
spec:
  type: ClusterIP
  ports:
  - name: nginx-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx

