apiVersion: batch/v1
kind: Job
metadata:
  name: oblicz-pi
  namespace: test1
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: oblicz-pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never

